# Generated by Django 4.2.6 on 2023-10-28 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('assigned_routes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEmployee',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('shift', models.TextField()),
                ('address', models.TextField()),
                ('geo_loc', models.TextField()),
                ('phone', models.TextField()),
                ('contracted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('shift', models.TextField()),
                ('address', models.TextField()),
                ('geo_loc', models.TextField()),
                ('phone', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.driver')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.route')),
            ],
        ),
    ]
