# Generated by Django 4.2.6 on 2023-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0002_remove_employee_geo_loc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trainingemployee',
            name='company',
            field=models.TextField(default=''),
        ),
    ]
