# Generated by Django 4.2.6 on 2023-10-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0003_employee_company_trainingemployee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='van',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.TextField(default=''),
        ),
    ]
