# Generated by Django 4.2.6 on 2023-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0004_rename_driver_id_employee_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='shift',
            field=models.TextField(default=''),
        ),
    ]
