# Generated by Django 4.2.6 on 2023-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0005_route_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='driver',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='route',
            new_name='route_id',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='driver',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='van',
            old_name='driver',
            new_name='driver_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='assigned_routes',
        ),
        migrations.AddField(
            model_name='route',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
