# Generated by Django 4.2.6 on 2023-11-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0006_rename_driver_employee_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='descr',
            field=models.TextField(default=''),
        ),
    ]
