# Generated by Django 4.2.6 on 2023-12-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0008_alter_driver__id_alter_employee__id_alter_route__id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='trainingemployee',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='van',
            old_name='_id',
            new_name='id',
        ),
    ]
