# Generated by Django 4.2.6 on 2023-12-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0009_rename__id_driver_id_rename__id_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
